会場を株式会社インプレスに更新した
sato-tk/ichiyasaGitSample pull request #1
Opened 2024-07-27 04:13 UTC by sato-tk

### 変更内容
イベント開催会場を「株式会社インプレス」に更新しました。

### 背景
「株式会社インプレス」さんがイベント会場を提供してくれることになりました。

2024-08-06 06:55 UTC, sato-tky commented
修正ありがとうございます！問題ないのでマージします。

2024-08-22 16:56 UTC, sato-tky requested changes
修正ありがとうございます！指摘のご確認と修正お願いします。

2024-09-05 03:37 UTC, sato-tk commented
ありがとうございました 👍

2024-09-05 03:41 UTC, sato-tky approved these changes

2024-09-17 12:21 UTC, merged